//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica02_EntityF_ADO_NET.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbViaje
    {
        public int idViaje { get; set; }
        public int idTarjeta { get; set; }
        public int idPais { get; set; }
        public System.DateTime fechaInicioViaje { get; set; }
        public System.DateTime fechaFinViaje { get; set; }
        public string estadoViaje { get; set; }
    
        public virtual tbPais tbPais { get; set; }
        public virtual tbTarjeta tbTarjeta { get; set; }
    }
}
